version: '3.9'
name: dipoassist

services:
  app:
    image: brilliahib/dipoassist-api:latest
    container_name: dipoassist-api
    restart: always
    env_file: .env
    ports:
      - '9000:9000'
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
