#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export FORCE_COLOR=1

npx commitlint --edit "$1" || (
  echo '✍📤 Your commit message does not follow the Conventional Commits format.'
  echo 'You can use "npm run commit" to help you create a properly formatted message.'
  exit 1
)
