#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export FORCE_COLOR=1
echo '🔍🎨 Formatting and checking staged files before committing!'

npx lint-staged || (
  echo '💀❌ Ooops! Formatting or checking failed!'
  exit 1
)

echo '🥳✅ All good! Proceeding to commit...'
